import os, sys
from playsound import playsound

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly,")
playsound("Intro_1.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
playsound("Centipede_1.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: ")
playsound("Intro_2.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
playsound("Spider_1.mp3")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\'")
playsound("Centipede_2.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
playsound("Intro_3.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
playsound("Centipede_3.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
print("And when I go to dancing-class on Saturdays at three,")
print("I find the First Position very difficult for me.")
print("Though I put my best foot foremost, and good time I try to keep,")
print("To my chagrin, I always find a foot or two asleep.")
print("")
playsound("Centipede_4.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
print("And when I go to dancing-class on Saturdays at three,")
print("I find the First Position very difficult for me.")
print("Though I put my best foot foremost, and good time I try to keep,")
print("To my chagrin, I always find a foot or two asleep.")
print("")
print("Athletics I attempted, but, alas! I must admit")
print("That every exercise I tried I put my foot in it.")
print("I think I\'ll join a foot-ball team,--as many friends suggest,--")
print("Before I\'ve one foot in the grave and gout in all the rest.")
print("")
playsound("Centipede_5.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
print("And when I go to dancing-class on Saturdays at three,")
print("I find the First Position very difficult for me.")
print("Though I put my best foot foremost, and good time I try to keep,")
print("To my chagrin, I always find a foot or two asleep.")
print("")
print("Athletics I attempted, but, alas! I must admit")
print("That every exercise I tried I put my foot in it.")
print("I think I\'ll join a foot-ball team,--as many friends suggest,--")
print("Before I\'ve one foot in the grave and gout in all the rest.")
print("")
print("But now I\'ll say good-morning; for, my friend, I have to stop")
print("To get my boots blacked neatly at this little boot-black\'s shop;")
print("And, as you may imagine, it will keep me here some time,")
print("But, what is worse, I'll have to pay him many a hard-earned dime.\'")
playsound("Centipede_6.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
print("And when I go to dancing-class on Saturdays at three,")
print("I find the First Position very difficult for me.")
print("Though I put my best foot foremost, and good time I try to keep,")
print("To my chagrin, I always find a foot or two asleep.")
print("")
print("Athletics I attempted, but, alas! I must admit")
print("That every exercise I tried I put my foot in it.")
print("I think I\'ll join a foot-ball team,--as many friends suggest,--")
print("Before I\'ve one foot in the grave and gout in all the rest.")
print("")
print("But now I\'ll say good-morning; for, my friend, I have to stop")
print("To get my boots blacked neatly at this little boot-black\'s shop;")
print("And, as you may imagine, it will keep me here some time,")
print("But, what is worse, I'll have to pay him many a hard-earned dime.\'")
print("")
print("The Spider said good-morning, and pursued his way alone,")
print("And as he went he murmured, in a thoughtful undertone:")
playsound("Intro_4.wav")

os.system("cls")

print("A Spider and a Centipede went out to take a walk;")
print("The Centipede said frankly, \'I will listen while you talk,")
print("But I may appear distracted, or assume a vacant stare,")
print("Because to keep my feet in step requires my constant care.\'")
print("")
print("Said the Spider: \'I appreciate your most peculiar case,")
print("And your feet must be quite handy when you want to run a race;")
print("But though you gain in some ways, in some other ways you lose;")
print("And, of course, my friend, you must be quite extravagant in shoes.\'")
print("")
print("\'Ah! yes. Ah! yes,\' a heavy sigh escaped the Centipede;")
print("\'And I have other trials, too;--my life is hard indeed!")
print("Why, sometimes when I\'m very tired, a long, long time it takes")
print("To ascertain with certainty which foot it is that aches.")
print("")
print("And when I go to dancing-class on Saturdays at three,")
print("I find the First Position very difficult for me.")
print("Though I put my best foot foremost, and good time I try to keep,")
print("To my chagrin, I always find a foot or two asleep.")
print("")
print("Athletics I attempted, but, alas! I must admit")
print("That every exercise I tried I put my foot in it.")
print("I think I\'ll join a foot-ball team,--as many friends suggest,--")
print("Before I\'ve one foot in the grave and gout in all the rest.")
print("")
print("But now I\'ll say good-morning; for, my friend, I have to stop")
print("To get my boots blacked neatly at this little boot-black\'s shop;")
print("And, as you may imagine, it will keep me here some time,")
print("But, what is worse, I'll have to pay him many a hard-earned dime.\'")
print("")
print("The Spider said good-morning, and pursued his way alone,")
print("And as he went he murmured, in a thoughtful undertone:")
print("\'I\'m a happy little Spider, and I'm very glad indeed,")
print("That I was born an octoped and not a centipede!\'")
print("")
playsound("Spider_2.mp3")

os.system("pause")
os.system("D:/engail/credits.mp4")
q = input()
